sonar.projectKey=shoppingcart-v5
sonar.projectName=ShoppingCart_v5
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# run with:
#    mvn clean verify sonar:sonar "-Dsonar.projectKey=shoppingcart-v4" "-Dsonar.token=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"